language: ruby
rvm:
- 2.1.7
env:
- DB=mysql
before_script:
- bundle exec rake test_app
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
notifications:
  slack:
    secure: GLjaki+Sxy703P/HsvG9Izmii8UaD0j9hu//MnzKxk6rJIFx5WAzK3EyAx1ktkPEXprFfkS2JDjqGlHm/Vr4FQa4uYZ22qiALmBF0/MQ3UDLga+ApOBJyATl8IqWxo5FuEhzvSedDEIa0ntysco2Ff+pc8A7m9TZT3PLNfEOI1pM46aTdiyE1Jnv4yX7d1I4WETdzxAk7lGbPdiLbDsoqd6Ra+8+bVHnSfMAQoe2dqhLTkOyH8Dib+qQSohbzPZu4wwcgAsDz5FS0BpWqscNNZIECEMTUNyG2u9WiUHO7p9OPGbAZ1/Kh9F2Dwtffmvleo7WtAHZlWR29klkRdTktnumJTkUCbKiDdh5qUnMzyDR5Pe4NYiF2Inggyf/WhYd1UKvJ0zaQ5gqmtgmQKd+6OSFsnOoLwmrnOiA761jDHC/xk33t0Qc0VadRT+QvBO6Ijok6qoeUOpDh0Tp+LOjXx/JCyUQdFa89H9jlNxgiZrA7t6dAaIL7QnqCALeksy4yq1L0NeTtDsg8Ypwc2VGcHri0E5NrVTu9P9u+3qZnsjfrtu++keBn43vxzBdVvaNjzeN0fkRVYA3Fn0bAc/7I7WDnLDvoBHPEusn/wcJEAlnV6O/Lz6sjSPkFILB/7VHw/q5avf+1RfQCvXI8SgvZEHRF1wDt01peqiAimjCRRk=
